import type { TemplateDefinition } from "../types";

export const TEMPLATE_DEFINITIONS: TemplateDefinition[] = [
  {
    id: "minimal-lower-third",
    version: "1.0.0",
    name: "Minimal bar + name",
    description: "Clean lower third with accent bar and two text lines.",
    category: "Lower thirds",
    tags: ["lower third", "minimal", "name"],
    aspectRatioHints: ["16:9", "9:16", "4:5", "1:1"],
    defaultDurationMs: 4500,
    direction: "rtl-capable",
    themeBindings: {
      accent: "colors.accent",
      text: "colors.onSurface",
      muted: "colors.muted",
    },
    exportHints: { prefersAlpha: true, supportsObsHtml: true },
    fields: [
      { key: "name", label: "Name", type: "text", default: "Alex Rivera", maxLength: 80, required: true },
      { key: "title", label: "Title / role", type: "text", default: "Creative Director", maxLength: 120 },
      { key: "accentColor", label: "Accent override", type: "color", default: "#22d3ee", kitToken: "colors.accent" },
      { key: "barWidth", label: "Bar width (px)", type: "number", default: 72, min: 4, max: 120 },
    ],
  },
  {
    id: "social-handle-strip",
    version: "1.0.0",
    name: "Social handle strip",
    description: "Platform label with @handle — great for cross-promos.",
    category: "Lower thirds",
    tags: ["social", "handle"],
    aspectRatioHints: ["16:9", "9:16"],
    defaultDurationMs: 4000,
    direction: "rtl-capable",
    themeBindings: { accent: "colors.accent", surface: "colors.surface" },
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "platform", label: "Platform label", type: "text", default: "Social", maxLength: 24 },
      { key: "handle", label: "Handle", type: "text", default: "@yourchannel", maxLength: 64, required: true },
    ],
  },
  {
    id: "guest-title-role",
    version: "1.0.0",
    name: "Guest + role",
    description: "Two-line identification with accent border.",
    category: "Lower thirds",
    tags: ["guest", "interview"],
    aspectRatioHints: ["16:9", "21:9"],
    defaultDurationMs: 4200,
    direction: "rtl-capable",
    themeBindings: { accent: "colors.accent" },
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "guestName", label: "Name", type: "text", default: "Jamie Chen", maxLength: 80, required: true },
      { key: "role", label: "Role / affiliation", type: "text", default: "Product Designer · Acme", maxLength: 120 },
    ],
  },
  {
    id: "subscribe-cta-card",
    version: "1.0.0",
    name: "Subscribe CTA card",
    description: "Generalized subscribe + bell motif with optional toast (not platform chrome).",
    category: "Call to action",
    tags: ["subscribe", "cta", "bell"],
    aspectRatioHints: ["16:9", "9:16"],
    defaultDurationMs: 5200,
    direction: "universal",
    themeBindings: { accent: "colors.accent", surface: "colors.surface" },
    exportHints: { prefersAlpha: true, supportsObsHtml: true },
    fields: [
      { key: "channelName", label: "Channel / brand name", type: "text", default: "Your Channel", maxLength: 64, required: true },
      { key: "subscriberLine", label: "Supporting line", type: "text", default: "Join the community", maxLength: 100 },
      { key: "toastText", label: "Toast text", type: "text", default: "New video · tap the bell", maxLength: 120 },
    ],
  },
  {
    id: "comment-prompt",
    version: "1.0.0",
    name: "Comment prompt",
    description: "Encourage discussion with a focused prompt.",
    category: "Call to action",
    tags: ["comment", "engagement"],
    aspectRatioHints: ["16:9", "9:16", "1:1"],
    defaultDurationMs: 4000,
    direction: "rtl-capable",
    themeBindings: { accent: "colors.accent" },
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "prompt", label: "Question / prompt", type: "text", default: "What would you try first?", maxLength: 140, required: true },
      { key: "cta", label: "Secondary line", type: "text", default: "Tell us in the comments", maxLength: 100 },
    ],
  },
  {
    id: "hero-title-stack",
    version: "1.0.0",
    name: "Hero title stack",
    description: "Center kinetic headline, pill subtitle, and tagline.",
    category: "Titles",
    tags: ["intro", "title", "kinetic"],
    aspectRatioHints: ["16:9", "9:16", "1:1"],
    defaultDurationMs: 5500,
    direction: "ltr-optimized",
    themeBindings: { accent: "colors.accent" },
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "title", label: "Main title", type: "text", default: "YOUR HEADLINE", maxLength: 48, required: true },
      { key: "subtitle", label: "Pill text", type: "text", default: "Kinetic title stack", maxLength: 48 },
      { key: "tagline", label: "Tagline", type: "text", default: "Clean motion · creator ready", maxLength: 96 },
      { key: "typingSpeed", label: "Typing speed", type: "number", default: 6, min: 1, max: 10 },
    ],
  },
  {
    id: "full-headline",
    version: "1.0.0",
    name: "Full-screen headline",
    description: "Large stacked headline for chapter or topic beats.",
    category: "Text scenes",
    tags: ["headline", "chapter"],
    aspectRatioHints: ["16:9", "9:16", "4:5"],
    defaultDurationMs: 4800,
    direction: "rtl-capable",
    themeBindings: {},
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "line1", label: "Line 1", type: "text", default: "FULL SCREEN", maxLength: 32, required: true },
      { key: "line2", label: "Line 2", type: "text", default: "HEADLINE", maxLength: 32 },
      { key: "subhead", label: "Subhead", type: "text", default: "Supporting line for context", maxLength: 120 },
    ],
  },
  {
    id: "numbered-list",
    version: "1.0.0",
    name: "Numbered list (3)",
    description: "Headline with three staggered list items.",
    category: "Text scenes",
    tags: ["list", "bullet"],
    aspectRatioHints: ["16:9", "9:16"],
    defaultDurationMs: 5000,
    direction: "rtl-capable",
    themeBindings: {},
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "headline", label: "Headline", type: "text", default: "Key takeaways", maxLength: 80, required: true },
      { key: "item1", label: "Item 1", type: "text", default: "Hook viewers in the first seconds", maxLength: 120 },
      { key: "item2", label: "Item 2", type: "text", default: "Keep pacing tight and purposeful", maxLength: 120 },
      { key: "item3", label: "Item 3", type: "text", default: "End with a clear next step", maxLength: 120 },
    ],
  },
  {
    id: "quote-card",
    version: "1.0.0",
    name: "Quote card",
    description: "Quote with attribution on a glass panel.",
    category: "Text scenes",
    tags: ["quote"],
    aspectRatioHints: ["16:9", "1:1", "4:5"],
    defaultDurationMs: 4500,
    direction: "rtl-capable",
    themeBindings: {},
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "quote", label: "Quote", type: "text", default: "Design is how it works.", maxLength: 280, required: true },
      { key: "attribution", label: "Attribution", type: "text", default: "— Creator name", maxLength: 80 },
    ],
  },
  {
    id: "definition-card",
    version: "1.0.0",
    name: "Definition card",
    description: "Term plus explanation — educational B-roll style.",
    category: "Text scenes",
    tags: ["definition", "edu"],
    aspectRatioHints: ["16:9", "9:16"],
    defaultDurationMs: 5000,
    direction: "rtl-capable",
    themeBindings: {},
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "term", label: "Term", type: "text", default: "Bitrate", maxLength: 64, required: true },
      {
        key: "definition",
        label: "Definition",
        type: "text",
        default: "Data processed per second of video.",
        maxLength: 400,
        required: true,
      },
    ],
  },
  {
    id: "timer-countdown",
    version: "1.0.0",
    name: "Timer (mm:ss)",
    description: "Countdown timer with progress bar.",
    category: "Utility",
    tags: ["timer", "countdown"],
    aspectRatioHints: ["16:9", "9:16", "1:1"],
    defaultDurationMs: 8000,
    direction: "universal",
    themeBindings: {},
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "label", label: "Label", type: "text", default: "Starting in", maxLength: 48 },
      { key: "startSeconds", label: "Start seconds", type: "number", default: 30, min: 5, max: 600 },
    ],
  },
  {
    id: "section-bumper",
    version: "1.0.0",
    name: "Section bumper",
    description: "Up next, Previously, or Chapter chip with title and subtitle.",
    category: "Titles",
    tags: ["bumper", "chapter", "series"],
    aspectRatioHints: ["16:9", "9:16", "1:1"],
    defaultDurationMs: 4200,
    direction: "rtl-capable",
    themeBindings: { accent: "colors.accent" },
    exportHints: { prefersAlpha: true },
    fields: [
      {
        key: "bumpKind",
        label: "Label style",
        type: "enum",
        default: "up_next",
        options: [
          { value: "up_next", label: "Up next" },
          { value: "previously", label: "Previously" },
          { value: "chapter", label: "Chapter" },
        ],
      },
      { key: "title", label: "Title", type: "text", default: "How we shipped v2", maxLength: 80, required: true },
      { key: "subtitle", label: "Subtitle", type: "text", default: "Episode 4 · Build", maxLength: 100 },
    ],
  },
  {
    id: "dual-guest-lower-third",
    version: "1.0.0",
    name: "Dual guest lower third",
    description: "Two name and role columns for interviews or panels.",
    category: "Lower thirds",
    tags: ["dual", "panel", "interview"],
    aspectRatioHints: ["16:9", "21:9"],
    defaultDurationMs: 4800,
    direction: "rtl-capable",
    themeBindings: { accent: "colors.accent" },
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "name1", label: "Guest 1 name", type: "text", default: "Alex Rivera", maxLength: 64, required: true },
      { key: "role1", label: "Guest 1 role", type: "text", default: "Host", maxLength: 80 },
      { key: "name2", label: "Guest 2 name", type: "text", default: "Jamie Chen", maxLength: 64, required: true },
      { key: "role2", label: "Guest 2 role", type: "text", default: "Designer · Acme", maxLength: 80 },
    ],
  },
  {
    id: "sponsor-disclosure",
    version: "1.0.0",
    name: "Sponsor / disclosure",
    description: "Presented-by line plus paid partnership or legal disclosure.",
    category: "Call to action",
    tags: ["sponsor", "ad", "disclosure"],
    aspectRatioHints: ["16:9", "9:16"],
    defaultDurationMs: 5000,
    direction: "rtl-capable",
    themeBindings: {},
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "brandLine", label: "Brand / title line", type: "text", default: "Presented by Acme Labs", maxLength: 100, required: true },
      {
        key: "disclosureLine",
        label: "Disclosure line",
        type: "text",
        default: "Paid partnership · Opinions are our own",
        maxLength: 140,
      },
    ],
  },
  {
    id: "poll-vs",
    version: "1.0.0",
    name: "Poll / vs",
    description: "Two-option A vs B with optional percentage labels.",
    category: "Call to action",
    tags: ["poll", "vote", "vs"],
    aspectRatioHints: ["16:9", "9:16", "1:1"],
    defaultDurationMs: 4500,
    direction: "rtl-capable",
    themeBindings: { accent: "colors.accent" },
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "optionA", label: "Option A", type: "text", default: "Ship fast", maxLength: 48, required: true },
      { key: "optionB", label: "Option B", type: "text", default: "Polish more", maxLength: 48, required: true },
      { key: "labelA", label: "Label A (e.g. 62%)", type: "text", default: "62%", maxLength: 12 },
      { key: "labelB", label: "Label B (e.g. 38%)", type: "text", default: "38%", maxLength: 12 },
    ],
  },
  {
    id: "product-price-callout",
    version: "1.0.0",
    name: "Product + price",
    description: "Product name, price, badge, and supporting line.",
    category: "Call to action",
    tags: ["product", "price", "commerce"],
    aspectRatioHints: ["16:9", "9:16", "4:5"],
    defaultDurationMs: 4400,
    direction: "rtl-capable",
    themeBindings: { accent: "colors.accent" },
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "productName", label: "Product name", type: "text", default: "Pro Headset X", maxLength: 64, required: true },
      { key: "price", label: "Price", type: "text", default: "$149", maxLength: 24, required: true },
      { key: "badge", label: "Badge", type: "text", default: "New", maxLength: 20 },
      { key: "subline", label: "Subline", type: "text", default: "Link in bio", maxLength: 80 },
    ],
  },
  {
    id: "location-date-stamp",
    version: "1.0.0",
    name: "Location + date",
    description: "Location, date, and optional time stamp for travel or events.",
    category: "Lower thirds",
    tags: ["location", "date", "vlog"],
    aspectRatioHints: ["16:9", "9:16"],
    defaultDurationMs: 4000,
    direction: "rtl-capable",
    themeBindings: {},
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "location", label: "Location", type: "text", default: "Lisbon, Portugal", maxLength: 64, required: true },
      { key: "dateLine", label: "Date", type: "text", default: "April 12, 2026", maxLength: 48 },
      { key: "timeLine", label: "Time (optional)", type: "text", default: "18:40 local", maxLength: 32 },
    ],
  },
  {
    id: "end-card-simple",
    version: "1.0.0",
    name: "End card",
    description: "Thanks line, tagline, and two optional footer lines.",
    category: "Titles",
    tags: ["outro", "thanks", "end"],
    aspectRatioHints: ["16:9", "9:16", "1:1"],
    defaultDurationMs: 5200,
    direction: "rtl-capable",
    themeBindings: { accent: "colors.accent" },
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "thanksLine", label: "Thanks line", type: "text", default: "Thanks for watching", maxLength: 64, required: true },
      { key: "tagline", label: "Tagline", type: "text", default: "New videos weekly", maxLength: 80 },
      { key: "line2", label: "Footer line 1", type: "text", default: "Subscribe for more", maxLength: 80 },
      { key: "line3", label: "Footer line 2", type: "text", default: "@yourchannel", maxLength: 80 },
    ],
  },
  {
    id: "step-progress",
    version: "1.0.0",
    name: "Step progress",
    description: "Step N of M with label and progress bar.",
    category: "Utility",
    tags: ["tutorial", "step", "progress"],
    aspectRatioHints: ["16:9", "9:16"],
    defaultDurationMs: 4500,
    direction: "rtl-capable",
    themeBindings: { accent: "colors.accent" },
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "stepLabel", label: "Step label", type: "text", default: "Export settings", maxLength: 80, required: true },
      { key: "stepIndex", label: "Current step", type: "number", default: 2, min: 1, max: 99 },
      { key: "stepTotal", label: "Total steps", type: "number", default: 5, min: 2, max: 99 },
    ],
  },
  {
    id: "breaking-live-strip",
    version: "1.0.0",
    name: "Live / breaking strip",
    description: "LIVE or breaking-style pill with two headline lines.",
    category: "Lower thirds",
    tags: ["live", "breaking", "news"],
    aspectRatioHints: ["16:9", "21:9"],
    defaultDurationMs: 4000,
    direction: "ltr-optimized",
    themeBindings: {},
    exportHints: { prefersAlpha: true },
    fields: [
      {
        key: "stripMode",
        label: "Mode",
        type: "enum",
        default: "live",
        options: [
          { value: "live", label: "LIVE" },
          { value: "breaking", label: "BREAKING" },
        ],
      },
      { key: "line1", label: "Headline", type: "text", default: "Special coverage", maxLength: 80, required: true },
      { key: "line2", label: "Secondary line", type: "text", default: "Updates as the story develops", maxLength: 120 },
    ],
  },
  {
    id: "calendar-event-card",
    version: "1.0.0",
    name: "Calendar event",
    description: "Date block, event title, and time for launches or webinars.",
    category: "Text scenes",
    tags: ["event", "calendar", "webinar"],
    aspectRatioHints: ["16:9", "9:16", "4:5"],
    defaultDurationMs: 4800,
    direction: "rtl-capable",
    themeBindings: { accent: "colors.accent" },
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "dateBlock", label: "Date block", type: "text", default: "APR 12", maxLength: 16, required: true },
      { key: "eventTitle", label: "Event title", type: "text", default: "Product launch livestream", maxLength: 80, required: true },
      { key: "timeLine", label: "Time / timezone", type: "text", default: "11:00 AM PT", maxLength: 48 },
    ],
  },
  {
    id: "keyboard-tip-overlay",
    version: "1.0.0",
    name: "Keyboard tip",
    description: "Shortcut keys plus short description for tutorials.",
    category: "Utility",
    tags: ["shortcut", "tip", "tutorial"],
    aspectRatioHints: ["16:9", "9:16"],
    defaultDurationMs: 3800,
    direction: "ltr-optimized",
    themeBindings: { accent: "colors.accent" },
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "keys", label: "Keys", type: "text", default: "⌘ + K", maxLength: 32, required: true },
      { key: "description", label: "Description", type: "text", default: "Open command palette", maxLength: 100 },
    ],
  },
  {
    id: "goal-bar-generic",
    version: "1.0.0",
    name: "Goal bar",
    description: "Label with current/target numbers and fill bar (generic, not platform UI).",
    category: "Call to action",
    tags: ["goal", "progress", "stream"],
    aspectRatioHints: ["16:9", "9:16"],
    defaultDurationMs: 5000,
    direction: "rtl-capable",
    themeBindings: { accent: "colors.accent" },
    exportHints: { prefersAlpha: true },
    fields: [
      { key: "goalLabel", label: "Label", type: "text", default: "Follower goal", maxLength: 48, required: true },
      { key: "currentVal", label: "Current (number)", type: "number", default: 12400, min: 0, max: 999999999 },
      { key: "targetVal", label: "Target (number)", type: "number", default: 15000, min: 1, max: 999999999 },
    ],
  },
];

export function definitionById(id: string): TemplateDefinition | undefined {
  return TEMPLATE_DEFINITIONS.find((d) => d.id === id);
}
